name: pennywise
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
description: A smart expense tracker app.
environment:
  sdk: ">=2.17.0 <3.0.0"

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
    
  
  shimmer: ^2.0.0
  provider: ^6.0.3
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  uuid: ^4.5.1
  flutter_colorpicker: ^1.1.0
  pie_chart: ^5.4.0

  flutter_dotenv: ^5.2.1
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.3.0
  flutter_signin_button: ^2.0.0
  google_generative_ai: ^0.4.6
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons:

flutter:
  assets:
      - .env
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
