name: pennywise
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
description: A smart expense tracker app.
environment:
  sdk: ">=2.17.0 <3.0.0"

version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^2.0.0

  provider: ^6.0.3
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  build_runner: ^2.4.15
  hive_generator: ^2.0.1
  uuid: ^4.5.1
  flutter_colorpicker: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true
